<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contract.Compiler\Contract.Compiler.csproj" />
    <ProjectReference Include="..\libs\Objekt-RT\src\ObjectRT.Runtime\ObjectRT.Runtime.csproj" />
    <ProjectReference Include="..\libs\ObjektRT.Stdlib\ObjektRT.Stdlib.csproj" />
  </ItemGroup>

</Project>
